# Set the prompt
# powerline-daemon -q
# POWERLINE_BASH_CONTINUATION=1
# POWERLINE_BASH_SELECT=1
# . /usr/share/powerline/bindings/bash/powerline.sh
PS1="\w > "

# Vars
EDITOR=nvim

# ----- Aliases ----- 
alias vim='nvim'
alias vi='nvim'

# ----- Custom functions -----
sd() { cd $(fd -Hat d | fzf) ;} # Search dirs from current dir
ef() { $EDITOR $(fzf) ;} # Edit files from current dir
vf() { less $(fzf) ;} # View files from current dir
