#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

wal -R >> /dev/null

xrdb ${HOME}/.config/urxvt/Xresources
xrdb -merge ${HOME}/.cache/wal/colors.Xresources

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start bar
${HOME}/.config/lemonbar/bar.sh | lemonbar -f "Hack Regular Nerd Font Complete:normal:size=10" -g 264x30+15+10
