---
  - name: Install xorg, bspwm, and sxhkd
    pacman:
      name:
        - bspwm
        - sxhkd
        - xf86-video-intel
        - xorg-apps
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
      state: present
  
  - name: Install basic applications
    pacman:
      name:
        - acpi
        - alsa-utils
        - base-devel
        - fd
        - feh
        - firefox
        - fzf
        - git
        - imagemagick
        - make
        - net-tools
        - networkmanager
        - nnn
        - nodejs
        - pass
        - pavucontrol
        - picom
        - python-pywal
        - powerline
        - powerline-fonts
        - pulseaudio
        - pulseaudio-alsa
        - pulseaudio-bluetooth
        - python-pip
        - rofi
        - rxvt-unicode
        - tmux 
        - xclip # For copying wth tmux
        - xdo # For bspwm swallow
      state: present
 
  - name: Install normal fonts
    pacman:
      name:
        - ttf-hack
        - wqy-microhei
      state: present

  - name: Clone StevenBlack's host file repo
    git:
      repo: 'https://github.com/StevenBlack/hosts.git'
      dest: /root/hosts
      force: yes

  - name: Copy host update systemd timer
    copy:
      src: "{{ item }}"
      dest: /usr/lib/systemd/system/
    with_items:
      - update-hosts.timer
      - update-hosts.service

  - name: Enable host update systemd timer
    service:
      name: update-hosts.timer
      state: started
      enabled: yes

  - name: Clone aur software repos
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://aur.archlinux.org/{{ item }}.git'
      dest: /home/{{ user }}/git_software/{{ item }}/
    with_items:
      - freetube-bin
      - nerd-fonts-hack
      - polybar

  - name: Clone rofi power menu
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://github.com/jluttine/rofi-power-menu.git'
      dest: /home/{{ user }}/git_software/rofi-power-menu/

  - name: Clone rofi pass menu
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://github.com/carnager/rofi-pass.git'
      dest: /home/{{ user }}/git_software/rofi-pass-menu/

  - name: Clone bspwm swallowing 
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://github.com/salman-abedin/bspwm_swallow.git'
      dest: /home/{{ user }}/git_software/bspwm_swallow/
        
  - name: Clone urxvt font size extension
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://github.com/majutsushi/urxvt-font-size.git'
      dest: /home/{{ user }}/git_software/urxvt-font-size/

  - name: Install aur software
    become: yes
    become_user: "{{ user }}"
    command: makepkg -si --noconfirm --noprogressbar
    args:
      chdir: /home/{{ user }}/git_software/{{ item }}/
    with_items:
      - freetube-bin
      - nerd-fonts-hack
      - polybar

  - name: Create paths for config files
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.config/{{ item }}
      state: directory
    with_items:
      - bspwm
      - lemonbar
      - picom
      - polybar
      - rofi
      - sxhkd
      - tmux
      - urxvt

  - name: Create path for urxvt extensions
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.urxvt/ext
      state: directory

  - name: Copy bashrc config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.{{ item }}
    with_items:
      - bashrc
 
  - name: Copy bspwm config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: bspwmrc
      dest: /home/{{ user }}/.config/bspwm/bspwmrc
      mode: '0755'

  - name: Copy picom config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: picom.conf
      dest: /home/{{ user }}/.config/picom/picom.conf
      mode: '0755'

  - name: Copy polybar config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.config/polybar/{{ item }}
      mode: '0755'
    with_items:
      - config
      - start_bar.sh
  
  - name: Copy rofi config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: config.rasi
      dest: /home/{{ user }}/.config/rofi/config.rasi

  - name: Copy rofi power menu mode
    copy:
      remote_src: yes
      src: /home/{{ user }}/git_software/rofi-power-menu/rofi-power-menu
      dest: /usr/local/bin/rofi-power-menu
      mode: '0755'

  - name: Copy rofi pass menu mode
    copy:
      remote_src: yes
      src: /home/{{ user }}/git_software/rofi-pass-menu/rofi-pass
      dest: /usr/local/bin/rofi-pass-menu
      mode: '0755'

  - name: Install bspwm swallow 
    make:
      chdir: /home/{{ user }}/git_software/bspwm_swallow/
      target: install

  - name: Copy urxvt font size script
    copy:
      remote_src: yes
      src: /home/{{ user }}/git_software/urxvt-font-size/font-size
      dest: /home/{{ user }}/.urxvt/ext/font-size
      mode: '0755'
  
  - name: Ensure en_US locale exists
    locale_gen:
      name: en_US.UTF-8
      state: present

  - name: Make sure Nerd font glyphs can display by setting the locale
    command: localectl set-locale LANG=en_US.UTF-8

  - name: Copy sxhkd config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: sxhkdrc
      dest: /home/{{ user }}/.config/sxhkd/sxhkdrc 
      mode: '0755'
  
  - name: Copy tmux config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: tmux.conf
      dest: /home/{{ user }}/.config/tmux/tmux.conf 
      mode: '0755'
        
  - name: Copy xinit config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: xinitrc
      dest: /home/{{ user }}/.xinitrc

  - name: Copy xresources config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: Xresources
      dest: /home/{{ user }}/.config/urxvt/Xresources
  
  - name: Create path for wallpapers
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/pictures/wallpapers
      state: directory

  - name: Copy wallpaper
    become: yes
    become_user: "{{ user }}"
    copy:
      src: broken_antennas.jpg
      dest: /home/{{ user }}/pictures/wallpapers
