---
- hosts: pc
  remote_user: root
  vars_files:
  - vars
  roles:
  - configure_users # Sets up user accounts
  - configure_desktop # Sets up window manager and desktop environment
  - configure_apps # Sets up user applications

# Installation steps:
# 1. Set up users and sudoers
# 2. Install dotfiles and dependencies
