---
  - name: Install neovim and plugin dependencies
    pacman:
      name:
        - bash
        - clang # For clangd language server
        - cmake
        - curl
        - fzf
        - git
        - gzip
        - neovim
        - nodejs
        - npm
        - perl
        - ripgrep
        - rustup
        - tar
        - unzip 
        - wget
        - xclip # For copying to the system clipboard
        - yarn
      state: present
  
  - name: Create path for Paq install
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.local/share/nvim/site/pack/paqs/start
      state: directory

  # - name: Install Paq
  #   become: yes
  #   become_user: "{{ user }}"
  #   git:
  #     repo: 'https://github.com/savq/paq-nvim.git'
  #     dest: /home/{{ user }}/.local/share/nvim/site/pack/paqs/start/paq-nvim
  #     force: yes
  
  - name: Create path for undo
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.config/nvim/undodir
      state: directory

  - name: Copy main neovim config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: init.lua
      dest: /home/{{ user }}/.config/nvim/init.lua
      mode: '0755'

  - name: Copy additional neovim config files
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.config/nvim/lua/
      mode: '0755'
    with_items:
      - general.lua
      - keys.lua
      - plugins.lua

  - name: Copy vim plugin config files
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.config/nvim/lua/plugin-conf/
      mode: '0755'
    with_items:
      - nvim-cmp.lua
      - nvim-lsp.lua
      - nvim-treesitter.lua
      - lualine.lua
