---
  - name: Install neovim and plugin dependencies
    pacman:
      name:
        - bash
        - clang # For clangd language server
        - cmake
        - curl
        - fzf
        - git
        - gzip
        - neovim
        - nodejs
        - npm
        - perl
        - ripgrep
        - tar
        - unzip 
        - wget
        - xclip # For copying to the system clipboard
        - yarn
      state: present
  
  - name: Create path for Paq install
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.local/share/nvim/site/pack/paqs/start
      state: directory

  - name: Install Paq
    become: yes
    become_user: "{{ user }}"
    git:
      repo: 'https://github.com/savq/paq-nvim.git'
      dest: /home/{{ user }}/.local/share/nvim/site/pack/paqs/start/paq-nvim
      force: yes
  
  - name: Create path for undo
    become: yes
    become_user: "{{ user }}"
    file:
      path: /home/{{ user }}/.config/nvim/undodir
      state: directory

  - name: Copy main neovim config file
    become: yes
    become_user: "{{ user }}"
    copy:
      src: init.lua
      dest: /home/{{ user }}/.config/nvim/init.lua
      mode: '0755'

  - name: Copy additional neovim config files
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.config/nvim/lua/
      mode: '0755'
    with_items:
      - general.lua
      - keys.lua
      - plug.lua

  - name: Copy vim plugin config files
    become: yes
    become_user: "{{ user }}"
    copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.config/nvim/lua/plug-confs/
      mode: '0755'
    with_items:
      - lspsaga-conf.lua
      - lualine-conf.lua
      - netrw-conf.lua
      - nvim-cmp-conf.lua
      - nvim-lspconfig-conf.lua
      - nvim-treesitter-conf.lua
      - telescope-conf.lua

  - name: Install language servers for LSP
    pacman:
      name:
        - bash-language-server
        - ccls
        - lua-language-server
        - pyright
        - rust-analyzer
      state: present

  - name: Install neovim plugins 
    become: yes
    become_user: "{{ user }}"
    shell:
      cmd: nvim +'PaqInstall --sync' +qa 
